apiVersion: v1
kind: Namespace
metadata:
    name: panoptes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: panoptes-editor
  namespace: panoptes
spec:
  selector:
    matchLabels:
      app: "panoptes-editor"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: panoptes-editor
    spec:
      containers:
      - image: pkourouklidis/model-editor:latest
        name: editor
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: resources-volume
          mountPath: /opt/app/resources
      volumes:
      - name: resources-volume
        persistentVolumeClaim:
          claimName: editor-resources
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: editor-resources
  namespace: panoptes
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
---
apiVersion: v1
kind: Service
metadata:
  name: panoptes-editor
  namespace: panoptes
spec:
  ports:
  - port: 8080
  selector:
    app: panoptes-editor
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: panoptes-editor
  namespace: panoptes
spec:
  hosts:
  - 'editor.panoptes.uk'
  gateways:
  - kubeflow/kubeflow-gateway
  http:
  - route:
    - destination:
        host: panoptes-editor
        port:
          number: 8080
---
apiVersion: eventing.knative.dev/v1
kind: broker
metadata:
  name: default
  namespace: panoptes
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: vulcan-registry-credentials
  namespace: panoptes
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5kb2NrZXIubmF0LmJ0LmNvbSI6eyJ1c2VybmFtZSI6IlNBMDczODk4IiwicGFzc3dvcmQiOiJ3emc4aHVxdCIsImVtYWlsIjoiYmV0YS5sYWJAYnQuY29tIiwiYXV0aCI6IlUwRXdOek00T1RnNmQzcG5PR2gxY1hRPSJ9fX0=
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: panoptes-registry-credentials
  namespace: panoptes
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5kb2NrZXIubmF0LmJ0LmNvbSI6eyJ1c2VybmFtZSI6InJvYm90JHBhbm9wdGVzU2V2aWNlQWNjb3VudDIiLCJwYXNzd29yZCI6ImV5SmhiR2NpT2lKU1V6STFOaUlzSW5SNWNDSTZJa3BYVkNKOS5leUpsZUhBaU9qRTJOak0zTlRZMk5EY3NJbWxoZENJNk1UWTJNVEUyTkRZME55d2lhWE56SWpvaWFHRnlZbTl5TFhSdmEyVnVMV1JsWm1GMWJIUkpjM04xWlhJaUxDSnBaQ0k2TWpFeU5EWXlMQ0p3YVdRaU9qVTFPQ3dpWVdOalpYTnpJanBiZXlKU1pYTnZkWEpqWlNJNklpOXdjbTlxWldOMEx6VTFPQzl5WlhCdmMybDBiM0o1SWl3aVFXTjBhVzl1SWpvaWNIVnphQ0lzSWtWbVptVmpkQ0k2SWlKOVhYMC5MNHpSRkFqdDhzOWgwb2VoeEtwc1JzdkVrQnMyTVgwNFZMWDVhUm1fQWdUdkJqczdvTDdadWZtaWY5UDZ3SmplcFJ6Q1lNWFpGdl8wczdZRS1odmx4MlkyOFNOeXE2Xzdxb3ExektsOGFoa1U0WmJnVV80SFZMRG1TLU5lc2ZDQ19WbUxnN3M5djVYZWs0bWlQcWd2b2ZRQk5KRGdLRVZWYWI3ZGsxVUxVZ3FoWW1CcjdVZUFBcHdCNFh5V2VGdzlaLW5yWGZMYXRTcktfbUw4Y2JFenRvZFdHVUdGWFZNYVY3OGxpNzQ5aUxzY1huRDVYRUFqeWF2YXVNaFpxa1YzTUlaUzRlWEtBdlFWSjFicGVheWhMT2RZbDdFVG9LVy03bkhmWXItcFA1N21QejBBbmllSW5CY3ZnLVd5MjNLTTJhSjliRHc0ZHhISkpRUzYxZ29DOGwwQ0ZienZxTllMMUVTMng2ODUwVkM1S005cjhZSGg3Y1NoVC1HdGoxSWpTTFQwTmYyZmJnRTh3ckk5SUxqNmJwTzlfX092MFFHTlBtYjAteHBRR0YtdEZjcWxYa2taV3VTcnhHaFpOYjAtQXJLZHA4RkR1aVIyVXB5RTh6aXoweWlJbFM2M190RDJUWHZvbEx0N2tpM0lwek5JZXVqaWU2dEtaLTh0eDRhWEc3N2VDdFNMLXFubkN5MlAxWG1BRDB3WHpCdXp5eWh2Y1pRY2xHODl3RF8xVU5mamNqdkl2ZkJWMm41Vi1mWjJ6ZEtsVVZoRnhhWU1ZcmRzcThSMVRIN3dWeXBWS0JjcHVCTENaaUZobkNISDR2RUo5TjFlbkZqOWdycXdVRG15Y01pbGUyQzZtejlua1kzUzQ2VmtDSXZuWTJRY2FCMWd2Y0dubk5JRG5KTSIsImVtYWlsIjoicGFuYWdpb3Rpcy5rb3Vyb3VrbGRpc0BidC5jb20iLCJhdXRoIjoiY205aWIzUWtjR0Z1YjNCMFpYTlRaWFpwWTJWQlkyTnZkVzUwTWpwbGVVcG9Za2RqYVU5cFNsTlZla2t4VG1sSmMwbHVValZqUTBrMlNXdHdXRlpEU2prdVpYbEtiR1ZJUVdsUGFrVXlUbXBOTTA1VVdUSk9SR056U1cxc2FHUkRTVFpOVkZreVRWUkZNazVFV1RCT2VYZHBZVmhPZWtscWIybGhSMFo1V1cwNWVVeFlVblpoTWxaMVRGZFNiRnB0UmpGaVNGSktZek5PTVZwWVNXbE1RMHB3V2tOSk5rMXFSWGxPUkZsNVRFTktkMkZYVVdsUGFsVXhUME4zYVZsWFRtcGFXRTU2U1dwd1ltVjVTbE5hV0U1MlpGaEthbHBUU1RaSmFUbDNZMjA1Y1ZwWFRqQk1lbFV4VDBNNWVWcFlRblpqTW13d1lqTktOVWxwZDJsUlYwNHdZVmM1ZFVscWIybGpTRlo2WVVOSmMwbHJWbTFhYlZacVpFTkpOa2xwU2psWVdEQXVURFI2VWtaQmFuUTRjemxvTUc5bGFIaExjSE5TYzNaRmEwSnpNazFZTURSV1RGZzFZVkp0WDBGblZIWkNhbk0zYjB3M1duVm1iV2xtT1ZBMmQwcHFaWEJTZWtOWlRWaGFSblpmTUhNM1dVVXRhSFpzZURKWk1qaFRUbmx4Tmw4M2NXOXhNWHBMYkRoaGFHdFZORnBpWjFWZk5FaFdURVJ0VXkxT1pYTm1RME5mVm0xTVp6ZHpPWFkxV0dWck5HMXBVSEZuZG05bVVVSk9Ta1JuUzBWV1ZtRmlOMlJyTVZWTVZXZHhhRmx0UW5JM1ZXVkJRWEIzUWpSWWVWZGxSbmM1V2kxdWNsaG1UR0YwVTNKTFgyMU1PR05pUlhwMGIyUlhSMVZIUmxoV1RXRldOemhzYVRjME9XbE1jMk5ZYmtRMVdFVkJhbmxoZG1GMVRXaGFjV3RXTTAxSldsTTBaVmhMUVhaUlZrb3hZbkJsWVhsb1RFOWtXV3czUlZSdlMxY3ROMjVJWmxseUxYQlFOVGR0VUhvd1FXNXBaVWx1UW1OMlp5MVhlVEl6UzAweVlVbzVZa1IzTkdSNFNFcEtVVk0yTVdkdlF6aHNNRU5HWW5wMmNVNVpUREZGVXpKNE5qZzFNRlpETlV0Tk9YSTRXVWhvTjJOVGFGUXRSM1JxTVVscVUweFVNRTVtTW1aaVowVTRkM0pKT1VsTWFqWmljRTg1WDE5UGRqQlJSMDVRYldJd0xYaHdVVWRHTFhSR1kzRnNXR3RyV2xkMVUzSjRSMmhhVG1Jd0xVRnlTMlJ3T0VaRWRXbFNNbFZ3ZVVVNGVtbDZNSGxwU1d4VE5qTmZkRVF5VkZoMmIyeE1kRGRyYVROSmNIcE9TV1YxYW1sbE5uUkxXaTA0ZEhnMFlWaEhOemRsUTNSVFRDMXhibTVEZVRKUU1WaHRRVVF3ZDFoNlFuVjZlWGxvZG1OYVVXTnNSemc1ZDBSZk1WVk9abXBqYW5aSmRtWkNWakp1TlZZdFpsb3llbVJMYkZWV2FFWjRZVmxOV1hKa2MzRTRVakZVU0RkM1ZubHdWa3RDWTNCMVFreERXbWxHYUc1RFNFZzBka1ZLT1U0eFpXNUdhamxuY25GM1ZVUnRlV05OYVd4bE1rTTJiWG81Ym10Wk0xTTBObFpyUTBsMmJsa3lVV05oUWpGbmRtTkhibTVPU1VSdVNrMD0ifX19
