apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default
  namespace: panoptes
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: event-transformer-request-trigger
  namespace: panoptes
spec:
  broker: default
  filter:
    attributes:
      type: org.kubeflow.serving.inference.request
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: event-transformer
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: orchestrator-sample-trigger
  namespace: panoptes
spec:
  broker: default
  filter:
    attributes:
      type: org.lowcomote.panoptes.trigger.sample
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: panoptes-orchestrator
    uri: /api/v1/events
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: python-function-runtime-algorithm-create
  namespace: panoptes
spec:
  broker: default
  filter:
    attributes:
      type: org.lowcomote.panoptes.baseAlgorithm.create
      subject: pythonFunction
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: python-function-runtime
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: python-function-runtime-algorithm-execution
  namespace: panoptes
spec:
  broker: default
  filter:
    attributes:
      type: org.lowcomote.panoptes.baseAlgorithmExecution.trigger
      subject: pythonFunction
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: python-function-runtime
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: orchestrator-base-algorithm-execution-result
  namespace: panoptes
spec:
  broker: default
  filter:
    attributes:
      type: org.lowcomote.panoptes.baseAlgorithmExecution.result
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: panoptes-orchestrator
    uri: /api/v1/events
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: email-action-trigger
  namespace: panoptes
spec:
  broker: default
  filter:
    attributes:
      type: org.lowcomote.panoptes.actionExecution.trigger
      subject: emailAction
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: email-action