apiVersion: apps/v1
kind: Deployment
metadata:
  name: retrain-action
  namespace: panoptes
spec:
  selector:
    matchLabels:
      app: retrain-action
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: retrain-action
    spec:
      containers:
      - image: registry.docker.nat.bt.com/panoptes/retrain-action:latest
        name: retrain-action
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: panoptes-registry-credentials
      serviceAccount: retrain-action
---
apiVersion: v1
kind: Service
metadata:
  name: retrain-action
  namespace: panoptes
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: retrain-action