apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: vulcan-registry-credentials
  namespace: panoptes
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5kb2NrZXIubmF0LmJ0LmNvbSI6eyJ1c2VybmFtZSI6IlNBMDczODk4IiwicGFzc3dvcmQiOiJ3emc4aHVxdCIsImVtYWlsIjoiYmV0YS5sYWJAYnQuY29tIiwiYXV0aCI6IlUwRXdOek00T1RnNmQzcG5PR2gxY1hRPSJ9fX0=
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: panoptes-registry-credentials
  namespace: panoptes
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5kb2NrZXIubmF0LmJ0LmNvbSI6eyJ1c2VybmFtZSI6InJvYm90JGdpdGxhYkFjY291bnQyIiwicGFzc3dvcmQiOiJleUpoYkdjaU9pSlNVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKbGVIQWlPakUyTmprNE1EY3hNeklzSW1saGRDSTZNVFkyTnpJeE5URXpNaXdpYVhOeklqb2lhR0Z5WW05eUxYUnZhMlZ1TFdSbFptRjFiSFJKYzNOMVpYSWlMQ0pwWkNJNk1qWTFOVEU0TENKd2FXUWlPalUxT0N3aVlXTmpaWE56SWpwYmV5SlNaWE52ZFhKalpTSTZJaTl3Y205cVpXTjBMelUxT0M5eVpYQnZjMmwwYjNKNUlpd2lRV04wYVc5dUlqb2ljSFZ6YUNJc0lrVm1abVZqZENJNklpSjlYWDAuUDJWb2wtaDg4LXpiZmI1VHp6SnI2eC1rMUxZVmxMdE9wejZ0MVF0RlV4THV5bGw2SWw1ZGQxVnBpUG43UXduTmFocFNMRWd0eUVWeWZLOE9nQXZEUFJyb1BLM2Q4R1ZJQl9xRFdNdzdwblhOUjJEajRsRU5tb2tPMERYMmZtcElEclpkUUwycEhmc2taendyc2gzWklOMnZOY1ZyNlFXVmVscWs4Uk5WMTZDbmJyNUd2UWZVRkFDNFJLXzJMemYtQk1BLUdkSlNkcVFRN09uc0YyMnVKZkVMdVl5NnRTYTJFajNhak5Zc3hEN1Nmd2duOHFUUHJEUTBMaTliMlhoaU5JOWdXZWwydDhzaEl0UVBSLU44YUJDbVE4LVFYOEhXd3BtbEw4MWZBa0pMb2dsdFNDNmczY0lQZ1hocURiempWUDJBMXNKV1VOMXBXUnJKSng1VFJUaHFNWXE5emktcjdwR21IMUxteEhNeFBtelJycFdJNmxlLVh0Q2VybUZLR3RwS1V5ZWRSalB5Um1NVUp0SWM2NE9mMWw5X2lNV3pDbHhnVXF1UWFsNUFDMnkxeXQ3cWVtTTNydjYyLUZSOWZpMFJ6RUpqbG5yb093Y0l2ZjZMTnplNnJWakE2WkZXUUsxajF1cWJHVlYwTXVVZEpxTEhYRHdUZmV2RV81WndKVU95SURGQVROektHcEtsaWRCUnBNUXA3dkdwNFc4cXoyLTZSaFFkbTlUSTFKemxLVFliQzlFUWtRYURZZGx2SjYzZThsbVhxQndMRDJBajNDSnBhSEZBZlA5U25ZVlg3VDRvdVU2TDlYYmFHZTRPME9NNnd6aktubTdzdFFfczNPeTh0U2ZuWWdXTTBuTXEzUnZTemw0SnVuYTFXMlRWTlRybVZiVThrc00ifX19
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-token
  namespace: panoptes  
type: Opaque
data:
  GITLAB_TOKEN: wnLgGSwcjFcy33A8EWNi