apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name:  panoptes-issuer
annotations:
spec:
  acme:
    email: panagiotis.kourouklidis@bt.com
    preferredChain: ""
    privateKeySecretRef:
      name: panoptes-issuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudDNS:
          project: bt-betalab-trn
          serviceAccountSecretRef:
            key: key.json
            name: clouddns-dns01-solver-svc-acct
      selector:
        dnsZones:
        - panoptes.betalab.rp.bt.com
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
      selector:
        dnsZones:
        - panoptes.uk

