apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  namespace: kubeflow-user-example-com
  name: callcenter
spec:
  predictor:
    serviceAccountName: sa
    minReplicas: 1
    sklearn:
      protocolVersion: "v2"
      runtimeVersion: "1.2.3-sklearn"
      resources:
        limits:
          cpu: 100m
          memory: 250Mi
        requests:
          cpu: 100m
          memory: 250Mi
      storageUri: s3://models/callcenter-linear/
    logger:
      mode: all
      url: http://broker-ingress.knative-eventing.svc.cluster.local/panoptes/default
---
apiVersion: v1
kind: Secret
metadata:
  namespace: kubeflow-user-example-com
  name: mysecret
  annotations:
     serving.kserve.io/s3-endpoint: minio-service.kubeflow.svc.cluster.local:9000 # replace with your s3 endpoint
     serving.kserve.io/s3-usehttps: "0" # by default 1, for testing with minio you need to set to 0
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bWluaW8=
  AWS_SECRET_ACCESS_KEY: bWluaW8xMjM=
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kubeflow-user-example-com
  name: sa 
secrets:
- name: mysecret
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  namespace: kubeflow-user-example-com
  name: allow-all
spec:
  action: ALLOW
  # This matches everything.
  rules:
  - {}