apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kubeflow-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 443
      name: https1 
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: kubeflow-cert
    hosts:
    - "kubeflow.panoptes.uk"
  - port:
      number: 443
      name: https2 
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: user-namespace-cert
    hosts:
    - "*.kubeflow-user-example-com.panoptes.uk"